### ISSUE TITLE
testclock SetTimerCallback is called unexpectedly when using contexts with deadlines

### ISSUE THREAD

**Issue by vadimsht** [luci/luci-go#11]
I'll explain on an example. Let's look at [retry_test.go](https://github.com/luci/luci-go/blob/master/common/retry/retry_test.go#L32):

```
ctx, c := testclock.UseTime(context.Background(), ...)

// Every time we sleep, update time by one second and count.
sleeps := 0
c.SetTimerCallback(func(time.Duration, clock.Timer) {
  c.Add(1 * time.Second)
  sleeps++
})
```

and modify it by adding deadline to the context:

```
ctx, c := testclock.UseTime(context.Background(), ...)
ctx, _ = clock.WithTimeout(ctx, 1000*time.Hour)

// Every time we sleep, update time by one second and count.
sleeps := 0
c.SetTimerCallback(func(time.Duration, clock.Timer) {
  c.Add(1 * time.Second)
  sleeps++
})
```

It is supposedly innocent change, since the deadline is far in the future.

What is expected: test still passes.
What happens: test fails because `SetTimerCallback` is called one extra time.

I've actually encountered this in another (uncommitted) test I'm writing. I use retry.Retry, and I try to fake time by doing:

```
clk.SetTimerCallback(func(d time.Duration, t clock.Timer) {
	clk.Add(d)
})
```

and I see it fast-forwards my test clock to the context deadline moment right away by calling the callback with context timeout as `d` (it is the second call of the callback). So instead of doing N retries, it does only 2.

Am I misusing testclock.SetTimerCallback?

**Comment by riannucci** [comment]
I don't think you're misusing it. However, @danjacques recently introduced a 'tagging' feature to timers so we can identify timers in the callback. We could use that to identify t as a "clock.ContextDeadline" timer in the callback and ignore it. I'm not sure if that's the right thing to do, but thinking about it it seems pretty reasonable.

**Comment by vadimsht** [comment]
Ugh... So IIUC, I'll need to tag contexts inside my "production" code (in places when I create additional contexts)? I can't find an existing usage example.

**Comment by riannucci** [comment]
I don't think there's another way to do it (in principle) that allows threaded execution. Somehow the test code needs to identify which timer it is, right?

**Comment by vadimsht** [comment]
Yeah... Another option is to avoid a need to identify timers by not using SetTimerCallback, and do time ticking relying on existing callbacks. E.g. if test knows that a sleep must happen, it schedules a time tick in advance (by posting to a channel or doing goroutine).

Tests are more complicated in that case (sometimes). But in my case it turned out to be very simple:

```
RetryCallback: func(err error, d time.Duration) {
	go clk.Add(d)
},
```

(where RetryCallback is ultimately called right before sleep by retry.Retry).

I can't find flaws in this approach in my case... Wdyt?

**Comment by riannucci** [comment]
The other thing to do could be to tag the timers that you care about identifying (and then in the callback check for the 'I care about this' tag).

I think that approach should work too, but it might be weird: the .Add would only be guaranteed to happen-before something which blocks on time's advancement. You could end up accumulating a whole bunch of those goroutines and then have them all run at once. I would probably nuke the `go` statement, if that's possible.

**Comment by vadimsht** [comment]
It deadlocks without `go` :-/ (because the following sleep uses `clock.Now` essentially, and so it doesn't care what value the clock had before it).

Actually, my approach works only because `go clk.Add` looses the race :( Crap.

**Comment by riannucci** [comment]
Oh, I see.. ick :(  I would try tagging that timer then. The TimerCallback as provided by test clock happens after the timer has 'blocked' on the 'current' time value, which allows it to be non-racy.

**Comment by vadimsht** [comment]
Ok, tagging works, but now I'm sad about unnecessary testing-related code executing in non-test scenarios (and about stringy-typing). But whatever.

**Comment by riannucci** [comment]
Well... clearly /something/ is necessary :P. This is what we have now... if you have ideas on how to make it better, we should do that. FWIW, the production clock implementation ignores all of the tag stuff (they're not even available in non-testclock, they go to /dev/null).

The stringy typing was done instead of some `[]interface{}` matchy stuff (and `[]string` is somewhat easier to debug than `[]interface{}`). The slice part was because if you e.g. create 4 timers on 4 threads, there needs to be some way to distinguish them (which you can do by tagging the context with some thread id in the current scheme, but if it was just interface{} you'd have to plumb that through everything)

**Comment by vadimsht** [comment]
I don't have any brilliant ideas :-/ Ideally, there should be zero overhead in using real clock => all mocking stuff should be exlcusively in test clock => clock.Tag(...) should be somehow part of test clock => perhaps clock can "tag" timers by using current (fake) timestamp of when they are created?.. Or some serial number. Since tests are supposedly deterministic, it could work, but would be extra brittle...

Another alternative is do some dirty stack frame evaluations to figure out where timer is created :)

As I said, I don't mind tags too much. My global concern is that by adding a little bit of overhead here, a bit there, etc. we can end up with slow monster (see Java, JVM is super fast, but Java code is not). But I'm not super concerned, because, you know, better than Python performance wise any way :)

**Comment by danjacques** [comment]
I considered stack trace, but that would be difficult b/c line numbers change etc. Tags as they currently stand are kind of a least-evil idea.


Another option may be to have the tag be passed to each timer on creation, maybe as an additional parameter (e.g., ...string). We would lose free inheritance, though, which is useful for differentiating goroutine A's sub-package's timer from goroutine B's, but it might be a compromise between perfect accuracy and reasonable performance/readability.

**Comment by riannucci** [comment]
I think maybe a sandwich like:
  * test adds something to context explicitly, maybe via a callback hook in the code (so now just nil-check in production instead of context alloc)
  * timer gets ...string parameter, and in testclock mode, it looks at the context one as well as the ...string one to create the full thingy.

Then the only required overhead in production is the function argument overhead (~zero), and in the event where you really need the stacky-ness of the contexts, you can still have them for the price of a nil-check in production.
