### ISSUE TITLE
Streaming up to client via WS or SSE

### ISSUE THREAD

**Issue by joeblew99** [luci/luci-go#16]
As I understand it,one of the functions supported is to expose grpc to web browsers.
If true, is there a potential to support streaming to browser ?

**Comment by riannucci** [comment]
Right now we only support unary rpcs (because streaming would be very hard
to emulate under appengine today). If it becomes feasible to implement
streaming on appengine at some point, we'll definitely look into it.

**Comment by joeblew99** [comment]
Ok thanks for clearing it.
