### ISSUE TITLE
No CIPD package for amv6l

### ISSUE THREAD

**Issue by erock2112** [luci/luci-go#21]
This is required for Skia's RPi lab in order to use CIPD packages.  Example error from a bot:

4631 2016-06-24 14:08:14.457 E: internal failure: Could not resolve version infra/tools/cipd/linux-armv6l:git_revision:d726bf1482f4fcfb1effce04bd924adef16fbdfc: status is PACKAGE_NOT_FOUND

**Comment by nodirt** [comment]
To clarify, skia needs a cipd client continuously built for arm.

**Comment by nodirt** [comment]
cc @vadimsht

**Comment by vadimsht** [comment]
The plan is to teach one of our Linux CI builders to also cross-compile subset of Go code (including cipd client) for ARM target. 

To do so we need:

- Teach go/bootstrap.py to optionally install cross-compilation-capable Go toolchain.
- Fix our code to not depend on libraries that doesn't work when cross-compiled (primary os/user, but there may be more).
- Teach build/build.py (script that uploads built CIPD packages)  to recognize cross-compilation environment (by picking correct value for ${platform}).
- Modify infra_continious.py recipe to do cross compilation and upload packages.

**Comment by vadimsht** [comment]
Step 1 seems unnecessary with go1.6. (It used to be necessary with at least go1.4).

**Comment by erock2112** [comment]
This seems to be done! Thanks!
