### ISSUE TITLE
Remove reference to chrome-infra-packages from luci-go

### ISSUE THREAD

**Issue by maruel** [luci/luci-go#26]
We need to make the following a flag (it is a constant):

```
cipd/client/cipd/client.go:     ServiceURL = "https://chrome-infra-packages.appspot.com"
```

This URL always be passed as a flag.

**Comment by vadimsht** [comment]
There's a flag for this already, ServiceURL is the default value.

I can remove it from Github code by converting 'main' into a library, linking to this library from infra.git, and building the binary from infra.git code. That way 'cipd' binary distributed by Chrome Infra would still have default value for -service-url pointing to chrome-infra-packages. Requiring users to type URL in each invocation of the tool is BS.

**Comment by maruel** [comment]
I don't know, all of the invocations for swarming and isolate always provide the URL and it's not dramatic. The only problem would be when it is used manually but I don't foresee this happening often.

**Comment by vadimsht** [comment]
It does happening often. Cipd client is part of infra.git solution, people use it when they debug issues with packages.

Another option is to add "cipd configure -service-url ..." that dumps a config file somewhere in ~/.config. Then in infra.git (already existing) DEPS hook just call it automatically.

**Comment by maruel** [comment]
isolate and swarming supports an environment variable to set a default value to the argument. I think that would be appropriate here too.

**Comment by erikus** [comment]
I like the suggestion in [#issuecomment-240518061](#issuecomment-240518061) and I've done it a lot. Teams can choose to use a generic version of the tool or roll their own main with whatever extras they want.

**Comment by vadimsht** [comment]
Fixed by https://github.com/luci/luci-go/commit/30709f33d05d958190d3c9f2c356cdf2afc3a085
