### ISSUE TITLE
Make Go 1.5 the default runtime.

### ISSUE THREAD

**Issue by danjacques** [luci/luci-go#3]
The Go world is moving faster than we are, and we're already 2.5 months behind the Go 1.5 release. The latest edge that I hit is that Go Managed VMs now use the Go 1.5 runtime, meaning code that doesn't build for 1.5 cannot be deployed. The latest AppEngine SDK is still on 1.4.2.

Minimally, this means that we need to solve a few "/internal/" import issues:
* Vadim filed an issue with [go-endpoints](https://github.com/GoogleCloudPlatform/go-endpoints/issues/101).
* I filed an issue with [google-api-go-generator](https://github.com/google/google-api-go-client/issues/112).

This solves my issues; what other obstacles stand between us and Go 1.5?

**Comment by shishkander** [comment]
The other one is me nailing down the poor isolating performance. See [bug 523009 Vadim has already filed on codesite](http://crbug.com/523009).

**Comment by shishkander** [comment]
Haven't we made 1.6 default already? + @vadimsht

**Comment by danjacques** [comment]
Yes, 1.6 is currently the default.
