### ISSUE TITLE
grpc.SupportPackageIsVersion3 issue

### ISSUE THREAD

**Issue by code4ghana** [luci/luci-go#34]
It appears that currently the go files generated from luci-go's discovery protos rely on [SupportPackageIsVersion3](https://github.com/luci/luci-go/blob/master/grpc/discovery/service.pb.go#L81), but the [grpc-go](https://github.com/grpc/grpc-go/blob/master/rpc_util.go#L481) repo has been updated to [SupportPackageIsVersion4](https://github.com/grpc/grpc-go/blob/master/rpc_util.go#L481).  This is causing compilation errors, could we get a recompiled version of the service.pb.go etc. please? I tried to recompile them them but it appears that protoc could not find the imports declared in those proto files.

Running `goapp serve server` results in`/golang/src/github.com/luci/luci-go/grpc/discovery/service.pb.go:81: undefined: grpc.SupportPackageIsVersion3`

**Comment by danjacques** [comment]
Thanks for pointing that out. Internally, we use [pinned](https://chromium.googlesource.com/infra/infra/+/master/go/deps.lock) versions of our dependencies, so this isn't something we've observed. I've put together some CLs to update our pins, and can hopefully push them through shortly.
