### ISSUE TITLE
prpc depends on cloud.google.com/go/pubsub; build broken

### ISSUE THREAD

**Issue by evanj** [luci/luci-go#38]
I'm trying to use the prpc package to set up an App Engine Standard client send gRPC requests to a server running in Container Engine. Right now, I'm running into the following build error if I do a "current" checkout:

```
# github.com/luci/luci-go/common/gcloud/pubsub
/src/devenv/gopath/src/github.com/luci/luci-go/common/gcloud/pubsub/quota.go:31: undefined: "cloud.google.com/go/pubsub".DefaultMaxPrefetch
```

This is because of the recent breaking changes to this API, as announced: https://groups.google.com/forum/#!topic/google-api-go-announce/aaqRDIQ3rvU/discussion

To workaround this, I checked out `f4eafa8cbb48e8ef5e23b542c3cb51cd1cbce787` in that repository. However, I think there are a few ways to fix this:

* Update the luci code to the latest version of the pubsub client
* Fix the `prpc` package to not depend on this, since it doesn't need pubsub or any of the other Google Cloud services. I *think* this is because `prpc/auth.go` depends on `github.com/luci/luci-go/server/auth`, which then depends on basically everything else in the `luci` repository. I think this could be fixed by pulling the authentication-related interfaces out into their own package, with minimal dependencies. However, I didn't try it to see if this would work.
* Publish "working" commits of the luci dependencies, so I didn't need to manually hunt for the correct commit in this repository to get it to work? I know this part of Go dependency management is a pain, and I haven't followed what the latest way to get this to work is.

Thanks for prpc! If this works for us, we might have a Python client implementation we will publish.

**Comment by vadimsht** [comment]
I'll remove dependency on github.com/luci/luci-go/server/auth. It's very heavyweight, as you've noticed, and not very reusable outside of LUCI environment.

For dependency management we use Glide (wrapped with some bells and whistles), but we store pins outside of luci-go repo (see https://chromium.googlesource.com/infra/infra/+/master/go/#Structure for some explanation). Our current pins are https://chromium.googlesource.com/infra/infra/+/master/go/deps.lock

**Comment by vadimsht** [comment]
The CL to remove the dependency: https://codereview.chromium.org/2759853002/

**Comment by evanj** [comment]
Wow ... uh... thanks! That was an impressively fast response and patch. Thanks for the details on how  this uses Glide, that is helpful. I'll do that for the moment, but I'm looking forward to having significantly fewer dependencies when your patch lands!

**Comment by riannucci** [comment]
Speaking of python implementations, I think we already have one that you might be able to cannabalize (or maybe we can use yours if it's in better shape 😁 ): https://chromium.googlesource.com/infra/infra/+/master/appengine/monorail/api/prpc/grpc

It's buried within the monorail code because that was the only client we had so far, so it may have some project-specific hacks, but @agable-chromium might be able to comment if it's in decent enough shape to use. We could (should) probably move it to https://github.com/luci/luci-py .

**Comment by evanj** [comment]
Interesting! Thanks for the link, that is very useful. I wish I knew about it before we started on our own hacky version since the approach seems extremely similar. :) However, it looks like this is only the server though? We currently need a client, since our experiment is a server running in Container Engine that we want to talk to from our App Engine app. Thanks though, still very helpful!

**Comment by riannucci** [comment]
Ah, yes, it is only a server implementation. I think the theory is that any clients we might need we'd write in go, but we wanted to start migrating some of our older python services to pRPC (so we could then transparently rewrite them in go later, because the server API would be constant).

Having generated python client code might be interesting though, for quick scripts (even in the long term) 😃 .

**Comment by evanj** [comment]
Thanks for the context. It sound like we have a similar goal: we (Bluecore Inc) have a fairly big Python App Engine app, and want it to inter-operate with Go stuff that isn't on App Engine. At the moment, it looks like the first use will likely have our existing Python app call out to new Go code. 

Similar to the server implementation: thanks to Python's duck typing, it doesn't look like we need to change the generated API at all. We just wrote a hacky Channel implementation that you can pass to the existing generated `Stub` class.

**Comment by evanj** [comment]
Thanks! I have confirmed that the latest master fixes the issue and definitely results in a smaller binary that builds a lot less stuff ; Thanks!

**Comment by danjacques** [comment]
Great, thanks for the confirmation. Internally, we build against a set of pinned deps, so once in a while upstream code changes to dependent repositories aren't noticed until we bump those pins. Thanks for providing advance notice there :)
