### ISSUE TITLE
Add an example usage to CIPD docs

### ISSUE THREAD

**Issue by kharland** [luci/luci-go#44]
It's not clear after reading the README for CIPD how I should use the CLI tool.  Does my package need to have a certain directory structure? Am I directly referencing some type of archive file to upload as a package?  Do I need to specify all of the arguments for my package on the command line or can I include something like a YAML file to configure my package for uploading?

In general, it would be nice to see more of the owners giving more love to the docs in the luci-* stack.  It's pretty difficult to understand how to get up and running with the various tools here using the README's alone, and I don't feel that it should be.

**Comment by danjacques** [comment]
That's a valid criticism, and documentation on some components, including CIPD, is definitely lacking.

The LUCI project uses `crbug.com` for bug tracking. Would you mind re-submitting this bug [here](https://bugs.chromium.org/p/chromium/issues/entry?components=Infra>Platform)?

Sorry for the trouble - we should definitely update this repository to note that it is no longer canonical and that we're using Chromium's tooling for bug tracking and patch submission.
