### ISSUE TITLE
Proposal: html/template helper library

### ISSUE THREAD

**Issue by vadimsht** [luci/luci-go#6]
So I want to use html/template, and I want following features:

1. In local environment (dev server, localhost) I want templates to be read from disk all the time, without server restart. For faster development speed.
1. In prod I want templates to be compiled only once and then reused.
1. I want templates to live close the source code that uses them. For example, if package server/stuff/ui implements some endpoints that serve HTML, I want templates to live in server/stuff/ui/templates. It's non trivial on GAE, since only files under directory with app.yaml gets deployed to GAE.

My proposal is to use go:generate to bundle all templates into *.go file close to the module that uses them. That way we don't need to mess with app.yaml, and server executables (for non GAE case) will be nice single files.

On dev environment the code can try to use $GOPATH to discover where files are on disk.

The downside is that it's possible to forget to run 'go generate' before commit. In theory, we can try to add pre-commit-go check that ensures "go generate ..." is noop, but in practice it is ugly (since "go generate" doesn't have --check-only option, so we'd need to copy package in a temp dir before running "go generate", or forget about pcg idempotency).

Wdyt?

**Comment by maruel** [comment]
Personally, I'd prefer to not have to go generate. I know I will forget. I agree point 3 makes everything more complex than necessary so I don't mind too much. But be sure to add a presubmit check as you noted. You can do it via an environment variable, cheezy but it'll work.

**Comment by vadimsht** [comment]
So GOPATH is hidden from dev server :-/ There are hacky workarounds, but they are really hacky.

I value property 3 (templates live close to the source) more than convenience of 1. At least for templates that belong to reusable packages (like auth stuff).

So my modified proposal:

1. Always use go:generate based approach for templates living in reusable libraries (server/*, appengine/*). It means, when developing a template, one has to call "go generate ./..." quite often. The assumption here is that average user of luci-go library won't be writing many such libraries, and thus won't be suffering from the need to use "go generate".
1. For templates living in GAE apps, use files on disk, as usual.
1. There possibly be a wrapper around "files on disk" to live-reload them on dev server, and keep them cached in prod. Though looks like dev server likes to restart itself whenever anything under app directory changes, so maybe it will be OK to always cache templates loaded from disk. Dev server will just restart on changes, effectively clearing the cache.

To clarify: I'm writing simple UI (one page really) for configuring server/auth/* stuff, and I don't want users of this library to put some custom entries in app.yaml to use this UI. So I'll use go:generate based approach for templates under server/auth/*.

**Comment by maruel** [comment]
After sleeping on this, I think I'm fine with go:generate all the way. This permits keeping a standalone executable on the non-GAE side that can be sent around safely.

Options for ease of maintenance:
- A Go unit test could be made to verify this manually. Each package having templates would copy-paste the unit test.
- The default build could check on startup the exact same thing but by iterating all the templates found. This could even be done in the init() in the generated code.

**Comment by vadimsht** [comment]
Good idea with unit test. It is autogenerated now too. I actually think it is enough to catch forgotten updates. (Additional value of doing the same in init() is low).
